name = "Ansible"
grammar = "yaml"
path_suffixes = ["yml", "yaml"]
line_comments = ["# "]
block_comment = ["", ""]
autoclose_before = "]})"
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
]
